# -*- coding: utf-8 -*-
from __future__ import annotations

EVIDENCE_MODE_ENTITY = "entity_fact"
EVIDENCE_MODE_NUMERIC = "numeric_fact"
EVIDENCE_MODE_DATE = "date_fact"
EVIDENCE_MODE_SCHEDULE = "schedule_fact"
EVIDENCE_MODE_EVENT = "event_result"
EVIDENCE_MODE_ROUTE = "route_fact"
EVIDENCE_MODE_POLICY = "policy_fact"

STRUCTURED_EVIDENCE_MODES = {
    EVIDENCE_MODE_NUMERIC,
    EVIDENCE_MODE_DATE,
    EVIDENCE_MODE_SCHEDULE,
}

HIGH_RISK_SUPPORTING_EVIDENCE_MODES = {
    EVIDENCE_MODE_NUMERIC,
    EVIDENCE_MODE_DATE,
    EVIDENCE_MODE_EVENT,
    EVIDENCE_MODE_ROUTE,
    EVIDENCE_MODE_SCHEDULE,
    EVIDENCE_MODE_POLICY,
}

SENTENCE_DIRECTNESS_DIRECT = "direct"
SENTENCE_DIRECTNESS_PARTIAL = "partial"
SENTENCE_DIRECTNESS_RELATED_ONLY = "related_only"

SENTENCE_DIRECTNESS_LEVELS = {
    SENTENCE_DIRECTNESS_DIRECT,
    SENTENCE_DIRECTNESS_PARTIAL,
    SENTENCE_DIRECTNESS_RELATED_ONLY,
}

POINT_STAGE_NO_CANDIDATE = "no_candidate_sentence"
POINT_STAGE_ROUTE_RELATION_MISSING = "route_relation_missing"
POINT_STAGE_RELATED_ONLY = "related_only_candidates"
POINT_STAGE_NO_DIRECT = "no_direct_candidate"
POINT_STAGE_DIRECT_TO_UNCERTAIN = "direct_to_uncertain_only"
POINT_STAGE_DIRECT_NOT_CONVERTED = "direct_not_converted"
POINT_STAGE_POINT_NOT_DIRECT = "point_not_direct"
POINT_STAGE_CONVERTED = "converted_to_support_refute"

POINT_CONVERSION_STAGES = {
    POINT_STAGE_NO_CANDIDATE,
    POINT_STAGE_ROUTE_RELATION_MISSING,
    POINT_STAGE_RELATED_ONLY,
    POINT_STAGE_NO_DIRECT,
    POINT_STAGE_DIRECT_TO_UNCERTAIN,
    POINT_STAGE_DIRECT_NOT_CONVERTED,
    POINT_STAGE_POINT_NOT_DIRECT,
    POINT_STAGE_CONVERTED,
}

COVERAGE_LEVEL_NONE = "none"
COVERAGE_LEVEL_WEAK = "weak"
COVERAGE_LEVEL_PARTIAL = "partial"
COVERAGE_LEVEL_MODERATE = "moderate"
COVERAGE_LEVEL_STRONG = "strong"

COVERAGE_LEVELS = {
    COVERAGE_LEVEL_NONE,
    COVERAGE_LEVEL_WEAK,
    COVERAGE_LEVEL_PARTIAL,
    COVERAGE_LEVEL_MODERATE,
    COVERAGE_LEVEL_STRONG,
}
